baseURL = 'https://jrrt2023.tolkiendil.com/'
languageCode = 'fr-fr'
title = 'Journées de Recherche et de Rencontres sur Tolkien'
theme = ['ananke', 'osm']

resourceDir = "../resources"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true
[languages]
  [languages.fr]
    title = "JRRT"
    weight = 1
    contentDir = "content/fr"
    [[languages.fr.menu.main]]
      url = "/fr/"
      name = "Accueil"
      weight = 10
    [[languages.fr.menu.main]]
      url = "/fr/programme"
      name = "Programme"
      weight = 20
    [[languages.fr.menu.main]]
      url = "/fr/inscription"
      name = "Inscription"
      weight = 30
    [[languages.fr.menu.main]]
      url = "/fr/pratique"
      name = "Pratique"
      weight = 40
    [[languages.fr.menu.main]]
      url = "/fr/apropos"
      name = "À Propos"
      weight = 50
  [languages.en]
    title = "JRRT2023 by Tolkiendil"
    weight = 2
    contentDir = "content/en"
    [[languages.en.menu.main]]
      url = "/en/"
      name = "Home"
      weight = 110
    [[languages.en.menu.main]]
      url = "/en/programme"
      name = "Programme"
      weight = 120
    [[languages.en.menu.main]]
      url = "/en/inscription"
      name = "Register"
      weight = 130
    [[languages.en.menu.main]]
      url = "/en/pratique"
      name = "Practical Info"
      weight = 140
    [[languages.en.menu.main]]
      url = "/en/apropos"
      name = "About Us"
      weight = 150
    # languageDirection = 'rtl' for Right-To-Left languages

[cascade]
  featured_image = 'images/hobbitholezoom2.png'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "images/logo_cercle_web.png"
  description = "Site pour la commémoration des 50 ans de la première traduction du Seigneur des Anneaux en français, organisé par l'association Tolkiendil"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  omit_header_text = true

[[params.ananke_socials]]
name = "twitter"
label = "Twitter"
url = "https://www.twitter.com/TolkiendilFR"

[[params.ananke_socials]]
name = "facebook"
label = "Facebook"
url = "https://www.facebook.com/Tolkiendil"

[[params.ananke_socials]]
name = "mastodon"
label = "Mastodon"
url = "https://piaille.fr/@tolkiendil"

[[params.ananke_socials]]
name = "youtube"
label = "YouTube"
url = "http://www.youtube.com/user/AssoTolkiendil"

[[params.ananke_socials]]
name = "instagram"
label = "Instagram"
url = "https://www.instagram.com/Tolkiendil"

[[params.ananke_socials]]
name = "discord"
label = "Discord"
url = "https://discord.gg/cafByTS"

[[params.ananke_socials]]
name = "twitch"
label = "Twitch"
url = "https://www.twitch.tv/AssoTolkiendil"
